using System;

namespace CivicSurvival.Core.Attributes
{
    /// <summary>
    /// Declares a cross-field invariant that must hold after deserialization.
    /// CIVIC337 analyzer warns if a class has [SerializationInvariant] but its
    /// Deserialize method doesn't call ValidateSerializationInvariants().
    ///
    /// Usage:
    /// <code>
    /// [SerializationInvariant("LockedBalance &lt;= Balance", "Locked exceeds available")]
    /// [SerializationInvariant("StartHour &lt;= GameHour", "Future start time")]
    /// public partial class MySystem : CivicSystemBase, IDefaultSerializable
    /// </code>
    ///
    /// Then in Deserialize, after all reads:
    /// <code>
    /// ValidateSerializationInvariants(); // generated by PersistSerializationGenerator
    /// </code>
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
    public sealed class SerializationInvariantAttribute : Attribute
    {
        /// <summary>C# boolean expression using field names. Evaluated after Deserialize.</summary>
        public string Expression { get; }

        /// <summary>Human-readable description for the log warning when invariant fails.</summary>
        public string Description { get; }

        public SerializationInvariantAttribute(string expression, string description = "")
        {
            Expression = expression;
            Description = description;
        }
    }
}
