/**
 * Auto-generated binding constants and value binding types.
 * Source: Tools/binding-manifest.generated.json
 * Run: node Tools/sync-binding-codegen.js
 */
export const B = {
    Group: "CivicSurvival",
    AaAmmo: "AaAmmo",
    AaBofors: "AaBofors",
    AaGepard: "AaGepard",
    AaHeritage: "AaHeritage",
    AaMaxAmmo: "AaMaxAmmo",
    AaPatriot: "AaPatriot",
    AaStations: "AaStations",
    AcceptLabel: "AcceptLabel",
    AcceptOfficialContract: "AcceptOfficialContract",
    AcceptShadyContract: "AcceptShadyContract",
    AcceptShadyEffectiveCost: "AcceptShadyEffectiveCost",
    AcceptShadyLockedReasonId: "AcceptShadyLockedReasonId",
    AcceptToast: "AcceptToast",
    ActiveContractsJson: "ActiveContractsJson",
    ActiveData: "ActiveData",
    ActiveId: "ActiveId",
    ActiveModalState: "ActiveModalState",
    ActivePriority: "ActivePriority",
    AffordProcurementLockedReasonId: "AffordProcurementLockedReasonId",
    AidDistribution: "AidDistribution",
    AidFundsAccessible: "AidFundsAccessible",
    AidFundsOffered: "AidFundsOffered",
    AidTierId: "AidTierId",
    AirDefensePlacement: "AirDefensePlacement",
    AirDefensePlacementRequest: "AirDefensePlacementRequest",
    AirDefenseState: "AirDefenseState",
    Altitude: "Altitude",
    ArchetypeId: "ArchetypeId",
    AreaKm2: "AreaKm2",
    ArenaLastRefreshResult: "ArenaLastRefreshResult",
    ArenaLeaderboard: "ArenaLeaderboard",
    ArenaRankTiers: "ArenaRankTiers",
    ArenaRefresh: "ArenaRefresh",
    ArenaWeekly: "ArenaWeekly",
    ArenaYourPosition: "ArenaYourPosition",
    ArenaYourWeeklyPosition: "ArenaYourWeeklyPosition",
    ArrestedAssetsSeized: "ArrestedAssetsSeized",
    ArrestedWalletAfter: "ArrestedWalletAfter",
    AssetsSeizedSnapshot: "AssetsSeizedSnapshot",
    AtRiskPlantCount: "AtRiskPlantCount",
    AttackCosts: "AttackCosts",
    AttackType: "AttackType",
    AttentionState: "AttentionState",
    AudienceFatigue: "AudienceFatigue",
    Author: "Author",
    AuthorName: "AuthorName",
    AutoCutMW: "AutoCutMW",
    AutoDispatchBlockedByVip: "AutoDispatchBlockedByVip",
    AutoDispatchEnabled: "AutoDispatchEnabled",
    AutoDispatchSheddedCount: "AutoDispatchSheddedCount",
    AutoDispatchShedMW: "AutoDispatchShedMW",
    AutoDispatchToggle: "AutoDispatchToggle",
    AutoDispatchToggleRequest: "AutoDispatchToggleRequest",
    AutoResupplyEnabled: "AutoResupplyEnabled",
    Available: "Available",
    AvailableLocales: "AvailableLocales",
    AvailableThemes: "AvailableThemes",
    AvgBlackoutHours: "AvgBlackoutHours",
    AvgInfection: "AvgInfection",
    AvgIntegrity: "AvgIntegrity",
    AvgResistance: "AvgResistance",
    AvgTrauma: "AvgTrauma",
    BackupCapacity: "BackupCapacity",
    BackupCharge: "BackupCharge",
    BackupPolicy: "BackupPolicy",
    BackupPolicyRequest: "BackupPolicyRequest",
    BackupPower: "BackupPower",
    BackupPowerState: "BackupPowerState",
    Balance: "Balance",
    BallisticInterceptBallisticOnly: "BallisticInterceptBallisticOnly",
    BallisticInterceptMixed: "BallisticInterceptMixed",
    BallisticStock: "BallisticStock",
    BallisticTargets: "BallisticTargets",
    BaseBribeCost: "BaseBribeCost",
    BaseDailyCost: "BaseDailyCost",
    BaseExodusRatePercentPerDay: "BaseExodusRatePercentPerDay",
    BaseInsiderCost: "BaseInsiderCost",
    BasePreset: "BasePreset",
    BestStreak: "BestStreak",
    BlackoutProbabilityPct: "BlackoutProbabilityPct",
    BlackoutRecoveries: "BlackoutRecoveries",
    BlackoutSource: "BlackoutSource",
    BlackoutVulnerability: "BlackoutVulnerability",
    BlockedReasonId: "BlockedReasonId",
    Body: "Body",
    BoforsAmmo: "BoforsAmmo",
    BoforsCount: "BoforsCount",
    BoforsCrew: "BoforsCrew",
    BoforsMaxAmmo: "BoforsMaxAmmo",
    BoforsPrice: "BoforsPrice",
    BribeAvailability: "BribeAvailability",
    BribeCost: "BribeCost",
    BribeRiskWarning: "BribeRiskWarning",
    BuckwheatState: "BuckwheatState",
    BuckwheatTons: "BuckwheatTons",
    Building: "Building",
    BuildingName: "BuildingName",
    BuildingsCutCount: "BuildingsCutCount",
    BuildingsDamaged: "BuildingsDamaged",
    BuildingsDestroyedThisWeek: "BuildingsDestroyedThisWeek",
    CallToArms: "CallToArms",
    CallToArmsLockedReasonId: "CallToArmsLockedReasonId",
    CallToArmsOnCooldown: "CallToArmsOnCooldown",
    CallToArmsRequest: "CallToArmsRequest",
    CalmHours: "CalmHours",
    CameraX: "CameraX",
    CameraZ: "CameraZ",
    CanAcceptShady: "CanAcceptShady",
    CanAffordProcurement: "CanAffordProcurement",
    CanBuyInsider: "CanBuyInsider",
    CanCallToArms: "CanCallToArms",
    CancelOperation: "CancelOperation",
    CanDeployHero: "CanDeployHero",
    CanDistribute: "CanDistribute",
    CanEvacuationRun: "CanEvacuationRun",
    CanKickbackRepair: "CanKickbackRepair",
    CanModernizeCorrupt: "CanModernizeCorrupt",
    CanModernizeHonest: "CanModernizeHonest",
    CanMunicipalRepair: "CanMunicipalRepair",
    CanPlaceDonorPatriot: "CanPlaceDonorPatriot",
    CanPlaceHeritageBofors: "CanPlaceHeritageBofors",
    CanPlacePaidBofors: "CanPlacePaidBofors",
    CanPlacePaidGepard: "CanPlacePaidGepard",
    CanPlacePaidPatriot: "CanPlacePaidPatriot",
    CanPrepareBlackout: "CanPrepareBlackout",
    CanPrepareDisinfo: "CanPrepareDisinfo",
    CanPrepareDrone: "CanPrepareDrone",
    CanRecallHero: "CanRecallHero",
    CanResupplyGuns: "CanResupplyGuns",
    CanResupplyPatriot: "CanResupplyPatriot",
    CanRun: "CanRun",
    CanSbuVisit: "CanSbuVisit",
    CanSetBackupPolicy: "CanSetBackupPolicy",
    CanSetHeroCounter: "CanSetHeroCounter",
    CanSetHeroLecturing: "CanSetHeroLecturing",
    CanSetProcurement100: "CanSetProcurement100",
    CanSetProcurement25: "CanSetProcurement25",
    CanSetProcurement50: "CanSetProcurement50",
    CanSetProcurement75: "CanSetProcurement75",
    CanShadowRepair: "CanShadowRepair",
    CanToggleConscription: "CanToggleConscription",
    CanToggleCounterOSINT: "CanToggleCounterOSINT",
    CanToggleTelemetry: "CanToggleTelemetry",
    CanUpgradeIntel: "CanUpgradeIntel",
    CapacityHeadroomMW: "CapacityHeadroomMW",
    CapacityMW: "CapacityMW",
    CasualtiesThisWeek: "CasualtiesThisWeek",
    Category: "Category",
    ChargesCount: "ChargesCount",
    ChoiceRequired: "ChoiceRequired",
    ChoiceType: "ChoiceType",
    CityDispatchableMW: "CityDispatchableMW",
    CitySchedule: "CitySchedule",
    CityScheduleAvailability: "CityScheduleAvailability",
    CitySchedulePeriodRequest: "CitySchedulePeriodRequest",
    CityStability: "CityStability",
    CityTreasury: "CityTreasury",
    CivilianDamage: "CivilianDamage",
    CivilianMunicipalRepairHours: "CivilianMunicipalRepairHours",
    CivilianRepair: "CivilianRepair",
    CivilianRepairRequest: "CivilianRepairRequest",
    CivilianShadowOpsRepairHours: "CivilianShadowOpsRepairHours",
    ClearErrors: "ClearErrors",
    CloseDonorConference: "CloseDonorConference",
    CognitiveActive: "CognitiveActive",
    CognitiveDistricts: "CognitiveDistricts",
    CognitiveState: "CognitiveState",
    CollapseThresholdHours: "CollapseThresholdHours",
    CommercePenalty: "CommercePenalty",
    CommercialMW: "CommercialMW",
    CommercialOff: "CommercialOff",
    CompromisedDistricts: "CompromisedDistricts",
    ComputedAtGameHours: "ComputedAtGameHours",
    ConscriptionLockedReasonId: "ConscriptionLockedReasonId",
    ConscriptionReactivationOnCooldown: "ConscriptionReactivationOnCooldown",
    ConscriptionToggle: "ConscriptionToggle",
    ConscriptionToggleRequest: "ConscriptionToggleRequest",
    ConstructionDaysLeft: "ConstructionDaysLeft",
    ConstructionDelay: "ConstructionDelay",
    Consumption: "Consumption",
    ContextData: "ContextData",
    Contractor: "Contractor",
    ContractType: "ContractType",
    CopyReport: "CopyReport",
    CorruptionScheme: "CorruptionScheme",
    CorruptionSchemeRequest: "CorruptionSchemeRequest",
    CorruptionScore: "CorruptionScore",
    CorruptionWindowActive: "CorruptionWindowActive",
    Cost: "Cost",
    CountermeasureChoice: "CountermeasureChoice",
    CountermeasuresPhase: "CountermeasuresPhase",
    CountermeasuresState: "CountermeasuresState",
    CounterOSINTActive: "CounterOSINTActive",
    CounterOSINTDailyCost: "CounterOSINTDailyCost",
    CounterOSINTLockedReasonId: "CounterOSINTLockedReasonId",
    CoveragePct: "CoveragePct",
    CrashDumps: "CrashDumps",
    CrisisDayNumber: "CrisisDayNumber",
    CrisisSweep: "CrisisSweep",
    CrisisSweepRequest: "CrisisSweepRequest",
    CrisisSweepState: "CrisisSweepState",
    CriticalHitsThisWeek: "CriticalHitsThisWeek",
    CurrentAct: "CurrentAct",
    CurrentJournalist: "CurrentJournalist",
    CurrentLocale: "CurrentLocale",
    CurrentOutputMW: "CurrentOutputMW",
    DailyCost: "DailyCost",
    DailyIncome: "DailyIncome",
    DamageDealt: "DamageDealt",
    DamagePercent: "DamagePercent",
    DaysRemaining: "DaysRemaining",
    DaysSurvived: "DaysSurvived",
    DebriefingCasualties: "DebriefingCasualties",
    DebriefingCrashed: "DebriefingCrashed",
    DebriefingDamageCost: "DebriefingDamageCost",
    DebriefingEfficiency: "DebriefingEfficiency",
    DebriefingHits: "DebriefingHits",
    DebriefingInfraDamageCost: "DebriefingInfraDamageCost",
    DebriefingIntercepted: "DebriefingIntercepted",
    DebriefingShotsFired: "DebriefingShotsFired",
    DebriefingTotalThreats: "DebriefingTotalThreats",
    DebriefingWave: "DebriefingWave",
    DebtBreakdown: "DebtBreakdown",
    DebtRestructured: "DebtRestructured",
    DebtWarning: "DebtWarning",
    Debug_AaAmmo: "debug_aaAmmo",
    Debug_ABTestProgress: "debug_abTestProgress",
    Debug_ABTestStatus: "debug_abTestStatus",
    Debug_AffectedDistricts: "debug_affectedDistricts",
    Debug_BlackoutDuration: "debug_blackoutDuration",
    Debug_BlackoutedMW: "debug_blackoutedMW",
    Debug_BlackoutPercent: "debug_blackoutPercent",
    Debug_BuildingsInBlackout: "debug_buildingsInBlackout",
    Debug_CityIntegrity: "debug_cityIntegrity",
    Debug_CityType: "debug_cityType",
    Debug_CommercePenalty: "debug_commercePenalty",
    Debug_CommercialMW: "debug_commercialMW",
    Debug_Consumption: "debug_consumption",
    Debug_CorruptionHeat: "debug_corruptionHeat",
    Debug_CorruptionHistory: "debug_corruptionHistory",
    Debug_CorruptionScore: "debugCorruptionScore",
    Debug_CurrentAct: "debug_currentAct",
    Debug_EnemyPressure: "debug_enemyPressure",
    Debug_EnemyStance: "debug_enemyStance",
    Debug_EnemyStanceName: "debug_enemyStanceName",
    Debug_ExodusActive: "debug_exodusActive",
    Debug_ExodusRatePercentPerDay: "debug_exodusRatePercentPerDay",
    Debug_GridCollapsed: "debug_gridCollapsed",
    Debug_GridRecoveryHours: "debug_gridRecoveryHours",
    Debug_GridStressHours: "debug_gridStressHours",
    Debug_GridWarfareUnlocked: "debug_gridWarfareUnlocked",
    Debug_GridZone: "debug_gridZone",
    Debug_GridZoneName: "debug_gridZoneName",
    Debug_HappinessPenalty: "debug_happinessPenalty",
    Debug_IndustrialMW: "debug_industrialMW",
    Debug_InfectionRate: "debug_infectionRate",
    Debug_MediaTrust: "debug_mediaTrust",
    Debug_MoraleFactor: "debug_moraleFactor",
    Debug_OfficeMW: "debug_officeMW",
    Debug_PersonalChronicleStatus: "debug_personalChronicleStatus",
    Debug_PowerBalance: "debug_powerBalance",
    Debug_PowerHistory: "debug_powerHistory",
    Debug_Production: "debug_production",
    Debug_ResidentialMW: "debug_residentialMW",
    Debug_SetAct: "debug_setAct",
    Debug_SeverityHistory: "debug_severityHistory",
    Debug_SeverityScore: "debug_severityScore",
    Debug_ShadowBalance: "debug_shadowBalance",
    Debug_ShadowDailyIncome: "debug_shadowDailyIncome",
    Debug_ShockLevel: "debug_shockLevel",
    Debug_ShockTier: "debug_shockTier",
    Debug_ShockTierName: "debug_shockTierName",
    Debug_StancePhase: "debug_stancePhase",
    Debug_StancePhaseName: "debug_stancePhaseName",
    Debug_TelemarathonActive: "debug_telemarathonActive",
    Debug_TotalDistricts: "debug_totalDistricts",
    Debug_TotalFled: "debug_totalFled",
    Debug_TrustLevel: "debug_trustLevel",
    Debug_WarDay: "debug_warDay",
    Debug_WaveInProgress: "debug_waveInProgress",
    Debug_WaveNumber: "debug_waveNumber",
    Debug_WavePhase: "debug_wavePhase",
    Debug_WavePhaseName: "debug_wavePhaseName",
    DebugDemolish1Building: "DebugDemolish1Building",
    DebugDemolishBuildingsToggle: "DebugDemolishBuildingsToggle",
    DebugDestroyAllDrones: "DebugDestroyAllDrones",
    DebugExplodeDrone: "DebugExplodeDrone",
    DebugForceCrash: "DebugForceCrash",
    DebugForceDayChange: "DebugForceDayChange",
    DebugForceGridCollapse: "DebugForceGridCollapse",
    DebugForceWave: "DebugForceWave",
    DebugGeneratePersonalChronicle: "DebugGeneratePersonalChronicle",
    DebugGlitchDrone: "DebugGlitchDrone",
    DebugKill500CiviliansNative: "DebugKill500CiviliansNative",
    DebugResetGridStress: "DebugResetGridStress",
    DebugRunPreset: "DebugRunPreset",
    DebugSetCityIntegrity: "DebugSetCityIntegrity",
    DebugSetCorruption: "DebugSetCorruption",
    DebugSetDusk: "DebugSetDusk",
    DebugSetEnemyPressure: "DebugSetEnemyPressure",
    DebugSetMidnight: "DebugSetMidnight",
    DebugSetMoraleFactor: "DebugSetMoraleFactor",
    DebugSetShock: "DebugSetShock",
    DebugSetStress: "DebugSetStress",
    DebugSetTrust: "DebugSetTrust",
    DebugSkipPhase: "DebugSkipPhase",
    DebugSpawn10Ballistics: "DebugSpawn10Ballistics",
    DebugSpawn1Ballistic: "DebugSpawn1Ballistic",
    DebugSpawn1Drone: "DebugSpawn1Drone",
    DebugSpawn25Drones: "DebugSpawn25Drones",
    DebugSpawnWaveDusk: "DebugSpawnWaveDusk",
    DebugTestExplosion: "DebugTestExplosion",
    DebugTestTracer: "DebugTestTracer",
    DebugToggleExodus: "DebugToggleExodus",
    DebugToggleStates: "DebugToggleStates",
    DebugToggleSystem: "DebugToggleSystem",
    DeclineProcurement: "DeclineProcurement",
    DefeatCause: "DefeatCause",
    DefensePolicyId: "DefensePolicyId",
    DefensePolicyName: "DefensePolicyName",
    DefensePolicyRequest: "DefensePolicyRequest",
    DeliveredMW: "DeliveredMW",
    Demand: "Demand",
    DeployHero: "DeployHero",
    DeployHeroLockedReasonId: "DeployHeroLockedReasonId",
    DifficultyPreset: "DifficultyPreset",
    DisasterDamagePercent: "DisasterDamagePercent",
    DischargingCount: "DischargingCount",
    DiscoveryRisk: "DiscoveryRisk",
    DismissArrested: "DismissArrested",
    DismissCollapseModal: "DismissCollapseModal",
    DismissCorruptionOffer: "DismissCorruptionOffer",
    DismissDebriefing: "DismissDebriefing",
    DismissDefeat: "DismissDefeat",
    DismissExodusWarning: "DismissExodusWarning",
    DismissFirstDonorAid: "DismissFirstDonorAid",
    DismissFirstStrike: "DismissFirstStrike",
    DismissFirstSuccessfulDefense: "DismissFirstSuccessfulDefense",
    DismissGeneratorEra: "DismissGeneratorEra",
    DismissGhostTown: "DismissGhostTown",
    DismissGridCollapse: "DismissGridCollapse",
    DismissGridCritical: "DismissGridCritical",
    DismissModLoadFailure: "DismissModLoadFailure",
    DismissRefugeeModal: "DismissRefugeeModal",
    DismissSpotterAlert: "DismissSpotterAlert",
    DismissToast: "DismissToast",
    DismissWarBegins: "DismissWarBegins",
    DismissWarFatigue: "DismissWarFatigue",
    DismissWhoStaysBehind: "DismissWhoStaysBehind",
    DistributeAid: "DistributeAid",
    DistributeLockedReasonId: "DistributeLockedReasonId",
    DistrictIndex: "DistrictIndex",
    DistrictInternetToggle: "DistrictInternetToggle",
    DistrictInternetToggleRequest: "DistrictInternetToggleRequest",
    DistrictName: "DistrictName",
    Districts: "Districts",
    DistrictShedMW: "DistrictShedMW",
    DistrictsOverrideCity: "DistrictsOverrideCity",
    DistrictToggle: "DistrictToggle",
    DistrictToggleRequest: "DistrictToggleRequest",
    DominantNarrative: "DominantNarrative",
    DonorActiveGenerators: "DonorActiveGenerators",
    DonorCooldownDays: "DonorCooldownDays",
    DonorDefenseAvailable: "DonorDefenseAvailable",
    DonorDefenseLockedReasonId: "DonorDefenseLockedReasonId",
    DonorDialog: "DonorDialog",
    DonorDialogActive: "DonorDialogActive",
    DonorDialogRequest: "DonorDialogRequest",
    DonorExpectedAid: "DonorExpectedAid",
    DonorFundsAmount: "DonorFundsAmount",
    DonorFundsAvailable: "DonorFundsAvailable",
    DonorFundsLockedReasonId: "DonorFundsLockedReasonId",
    DonorGeneratorCount: "DonorGeneratorCount",
    DonorGeneratorMW: "DonorGeneratorMW",
    DonorPatriotCredits: "DonorPatriotCredits",
    DonorPatriotDays: "DonorPatriotDays",
    DonorPatriotLockedReasonId: "DonorPatriotLockedReasonId",
    DonorPowerAvailable: "DonorPowerAvailable",
    DonorPowerLockedReasonId: "DonorPowerLockedReasonId",
    DonorSelection: "DonorSelection",
    DonorSelectionRequest: "DonorSelectionRequest",
    DonorState: "DonorState",
    DonorStatus: "DonorStatus",
    DonorUsesRemaining: "DonorUsesRemaining",
    DroneInterceptBallisticOnly: "DroneInterceptBallisticOnly",
    DroneInterceptMixed: "DroneInterceptMixed",
    DroneStock: "DroneStock",
    EarlyWarningMessage: "EarlyWarningMessage",
    EffectiveCityMode: "EffectiveCityMode",
    EffectiveCost: "EffectiveCost",
    EffectiveDiagnostics: "EffectiveDiagnostics",
    EmergencyFundAvailability: "EmergencyFundAvailability",
    EmergencyFundBalance: "EmergencyFundBalance",
    EmergencyFundWithdraw: "EmergencyFundWithdraw",
    EmergencyResupply: "EmergencyResupply",
    EmergencyResupplyRequest: "EmergencyResupplyRequest",
    EndlessMode: "EndlessMode",
    EndlessModeRequest: "EndlessModeRequest",
    EnemyDigitalAxis: "EnemyDigitalAxis",
    EnemyInterceptChance: "EnemyInterceptChance",
    EnemyPhysicalAxis: "EnemyPhysicalAxis",
    EnemySocialAxis: "EnemySocialAxis",
    EnergyFocusRange: "EnergyFocusRange",
    Entity: "Entity",
    EntityIndex: "EntityIndex",
    EntityVersion: "EntityVersion",
    ErrorCount: "ErrorCount",
    EstimatedBallistics: "EstimatedBallistics",
    EstimatedCost: "EstimatedCost",
    EstimatedShaheds: "EstimatedShaheds",
    Eta: "Eta",
    Evacuation: "Evacuation",
    EvacuationCost: "EvacuationCost",
    EvacuationRunLockedReasonId: "EvacuationRunLockedReasonId",
    EvasionStatus: "EvasionStatus",
    ExecuteOperation: "ExecuteOperation",
    ExodusActive: "ExodusActive",
    ExodusRatePercentPerDay: "ExodusRatePercentPerDay",
    Expenses: "Expenses",
    ExportAvailability: "ExportAvailability",
    ExportedMW: "ExportedMW",
    ExportPercent: "ExportPercent",
    ExportState: "ExportState",
    FeatureWaveManifest: "FeatureWaveManifest",
    FinanceState: "FinanceState",
    FireCount: "FireCount",
    FleetSaturationFactor: "FleetSaturationFactor",
    FloorHits: "FloorHits",
    FocusNextThreat: "FocusNextThreat",
    FocusRadarDefense: "FocusRadarDefense",
    FocusRadarThreat: "FocusRadarThreat",
    FocusThreat: "FocusThreat",
    ForcedOffMW: "ForcedOffMW",
    FreeHeritageGrant: "FreeHeritageGrant",
    FreezeReason: "FreezeReason",
    FuelAvailabilityPercent: "FuelAvailabilityPercent",
    FuelFactor: "FuelFactor",
    FuelSiphonAvailability: "FuelSiphonAvailability",
    FuelSiphonPercent: "FuelSiphonPercent",
    GameHour: "GameHour",
    GenerationSources: "GenerationSources",
    GeneratorsRunning: "GeneratorsRunning",
    GepardAmmo: "GepardAmmo",
    GepardCount: "GepardCount",
    GepardCrew: "GepardCrew",
    GepardMaxAmmo: "GepardMaxAmmo",
    GepardPrice: "GepardPrice",
    GlobalConnected: "GlobalConnected",
    GlobalConnectionStatus: "GlobalConnectionStatus",
    GlobalOnlineHour: "GlobalOnlineHour",
    GlobalOnlineNow: "GlobalOnlineNow",
    GlobalOnlineToday: "GlobalOnlineToday",
    GlobalOnlineTotal: "GlobalOnlineTotal",
    GraceWindowHours: "GraceWindowHours",
    GridExportMW: "GridExportMW",
    GridFrequency: "GridFrequency",
    GridHelpSeen: "GridHelpSeen",
    GridStatus: "GridStatus",
    GridWarfareState: "GridWarfareState",
    GridWarfareUnlocked: "GridWarfareUnlocked",
    GunsResupplyCost: "GunsResupplyCost",
    HasBlockedItems: "HasBlockedItems",
    HasExploded: "HasExploded",
    HasInsider: "HasInsider",
    HasInternet: "HasInternet",
    HasProgram: "HasProgram",
    HasResult: "HasResult",
    HeadroomWarningMW: "HeadroomWarningMW",
    Heat: "Heat",
    HeatLevel: "HeatLevel",
    HeritageAmmo: "HeritageAmmo",
    HeritageBoforsCount: "HeritageBoforsCount",
    HeritageBoforsLockedReasonId: "HeritageBoforsLockedReasonId",
    HeritageCredits: "HeritageCredits",
    HeritageCreditsMax: "HeritageCreditsMax",
    HeritageCrew: "HeritageCrew",
    HeritageMaxAmmo: "HeritageMaxAmmo",
    HeroAction: "HeroAction",
    HeroActionRequest: "HeroActionRequest",
    HeroDeployCost: "HeroDeployCost",
    HeroInfectionReduction: "HeroInfectionReduction",
    HeroRecoveryBonus: "HeroRecoveryBonus",
    HeroStatus: "HeroStatus",
    HitCount: "HitCount",
    HospitalsPowered: "HospitalsPowered",
    HospitalsTotal: "HospitalsTotal",
    HouseholdsInfected: "HouseholdsInfected",
    HouseholdsUnderBlackout: "HouseholdsUnderBlackout",
    HouseholdsUnderImpact: "HouseholdsUnderImpact",
    HouseholdsWithEnvy: "HouseholdsWithEnvy",
    Icon: "Icon",
    Id: "Id",
    IdentifyConfirmed: "IdentifyConfirmed",
    IdentifyFocusActive: "IdentifyFocusActive",
    IdentifyProgress: "IdentifyProgress",
    IdentifyTrackedEntity: "IdentifyTrackedEntity",
    ImportState: "ImportState",
    Income: "Income",
    Index: "Index",
    IndustrialMW: "IndustrialMW",
    IndustrialOff: "IndustrialOff",
    InfectionRate: "InfectionRate",
    InfraFocusRange: "InfraFocusRange",
    InsiderCost: "InsiderCost",
    InsiderLockedReasonId: "InsiderLockedReasonId",
    InsiderRequest: "InsiderRequest",
    Integrity: "Integrity",
    IntelPurchase: "IntelPurchase",
    IntelReportLabel: "IntelReportLabel",
    IntelState: "IntelState",
    IntelUpgrade: "IntelUpgrade",
    IntelUpgradeCost: "IntelUpgradeCost",
    IntelUpgradeLevel: "IntelUpgradeLevel",
    IntelUpgradeLockedReasonId: "IntelUpgradeLockedReasonId",
    IntelUpgradeRequest: "IntelUpgradeRequest",
    InternetDisabled: "InternetDisabled",
    InternetMode: "InternetMode",
    InternetModeRequest: "InternetModeRequest",
    IntroHudVisible: "IntroHudVisible",
    IntroPhase: "IntroPhase",
    InvestigationProgress: "InvestigationProgress",
    IpsoActive: "IpsoActive",
    IpsoDistrictCount: "IpsoDistrictCount",
    IpsoIntensity: "IpsoIntensity",
    IpsoTotalDistricts: "IpsoTotalDistricts",
    IsAiGenerated: "IsAiGenerated",
    IsArrested: "IsArrested",
    IsAtRisk: "IsAtRisk",
    IsAutoShedded: "IsAutoShedded",
    IsCompromised: "IsCompromised",
    IsConscriptionActive: "IsConscriptionActive",
    IsDestroyed: "IsDestroyed",
    IsExpanded: "IsExpanded",
    IsFrozen: "IsFrozen",
    IsFrozenOut: "IsFrozenOut",
    IsIdentified: "IsIdentified",
    IsInShock: "IsInShock",
    IsManpowerCritical: "IsManpowerCritical",
    IsManpowerOvercommitted: "IsManpowerOvercommitted",
    IsMassiveStrike: "IsMassiveStrike",
    IsOfficial: "IsOfficial",
    IsRecoverableBallisticOnly: "IsRecoverableBallisticOnly",
    IsRecoverableMixed: "IsRecoverableMixed",
    IsRepairable: "IsRepairable",
    IsRepairing: "IsRepairing",
    IsSanctioned: "IsSanctioned",
    IsShady: "IsShady",
    IsUncensored: "IsUncensored",
    IsUnderConstruction: "IsUnderConstruction",
    IsUnzoned: "IsUnzoned",
    IsVIP: "IsVIP",
    IsVIPBypass: "IsVIPBypass",
    IsWarFatigued: "IsWarFatigued",
    JsLog: "JsLog",
    KickbackAmount: "KickbackAmount",
    KickbackEarned: "KickbackEarned",
    KickbackOffer: "KickbackOffer",
    KickbackRepairAmount: "KickbackRepairAmount",
    KickbackRepairLockedReasonId: "KickbackRepairLockedReasonId",
    LanguagePreference: "LanguagePreference",
    LastChoiceRequestResult: "LastChoiceRequestResult",
    LastChoiceResult: "LastChoiceResult",
    LastDistributeResult: "LastDistributeResult",
    LaunchDistrictModernization: "LaunchDistrictModernization",
    LegalExportMW: "LegalExportMW",
    LegalImportMW: "LegalImportMW",
    Lifetime: "Lifetime",
    LoansAvailable: "LoansAvailable",
    LocaleChange: "LocaleChange",
    LocaleRequest: "LocaleRequest",
    LocaleVersion: "LocaleVersion",
    LocalizationStrings: "LocalizationStrings",
    LockedBalance: "LockedBalance",
    LockedReasonId: "LockedReasonId",
    MaintenanceContract: "MaintenanceContract",
    MaintenanceContractRequest: "MaintenanceContractRequest",
    MaintenanceState: "MaintenanceState",
    MakeInvestigationChoice: "MakeInvestigationChoice",
    MakePoliceChoice: "MakePoliceChoice",
    ManpowerAvailable: "ManpowerAvailable",
    ManpowerBasePool: "ManpowerBasePool",
    ManpowerCasualties: "ManpowerCasualties",
    ManpowerFatigueFactor: "ManpowerFatigueFactor",
    ManpowerMoraleFactor: "ManpowerMoraleFactor",
    ManpowerPatriotismFactor: "ManpowerPatriotismFactor",
    ManpowerPercent: "ManpowerPercent",
    ManpowerTotal: "ManpowerTotal",
    ManpowerUsed: "ManpowerUsed",
    MapBounds: "MapBounds",
    MapContour: "MapContour",
    MarkGridHelpSeen: "MarkGridHelpSeen",
    MarkShadowHelpSeen: "MarkShadowHelpSeen",
    Max: "Max",
    MaxHits: "MaxHits",
    MaxHours: "MaxHours",
    MaxShadowImportMW: "MaxShadowImportMW",
    MaxX: "MaxX",
    MaxZ: "MaxZ",
    MedianCollapseDay: "MedianCollapseDay",
    MediaTrust: "MediaTrust",
    Message: "Message",
    Min: "Min",
    MinEtaSeconds: "MinEtaSeconds",
    MinFloorHits: "MinFloorHits",
    MinHours: "MinHours",
    MinX: "MinX",
    MinZ: "MinZ",
    MissilesIntercepted: "MissilesIntercepted",
    MissilesSpentOnDrones: "MissilesSpentOnDrones",
    Mobilization: "Mobilization",
    MobilizationState: "MobilizationState",
    Mode: "Mode",
    Modernization: "Modernization",
    ModernizationRequest: "ModernizationRequest",
    ModernizeCorruptLockedReasonId: "ModernizeCorruptLockedReasonId",
    ModernizeHonestLockedReasonId: "ModernizeHonestLockedReasonId",
    Mood: "Mood",
    MunicipalKickbackRepairCharge: "MunicipalKickbackRepairCharge",
    MunicipalRepairCharge: "MunicipalRepairCharge",
    MunicipalRepairLockedReasonId: "MunicipalRepairLockedReasonId",
    MuteAlertAudio: "MuteAlertAudio",
    MuteCivicAudio: "MuteCivicAudio",
    MuteCombatAudio: "MuteCombatAudio",
    MuteDroneAudio: "MuteDroneAudio",
    Name: "Name",
    NarrativeMode: "NarrativeMode",
    NeighborEnvy: "NeighborEnvy",
    NetworkConnectionEnabled: "NetworkConnectionEnabled",
    NewsFeed: "NewsFeed",
    NewsState: "NewsState",
    Nickname: "Nickname",
    NicknameChangesRemaining: "NicknameChangesRemaining",
    NicknameInitialized: "NicknameInitialized",
    NicknameRequest: "NicknameRequest",
    NicknameUpdate: "NicknameUpdate",
    NoActiveThreatsLabel: "NoActiveThreatsLabel",
    NoiseLevel: "NoiseLevel",
    ObjectiveProgress: "ObjectiveProgress",
    OfferFrequencyMult: "OfferFrequencyMult",
    OfficeMW: "OfficeMW",
    OfficeOff: "OfficeOff",
    OfficialPrice: "OfficialPrice",
    OfficialQuality: "OfficialQuality",
    OfficialTreasury: "OfficialTreasury",
    OfficialVendorName: "OfficialVendorName",
    OffshoreBalance: "OffshoreBalance",
    OnAcceptReality: "OnAcceptReality",
    OneMoreYear: "OneMoreYear",
    OneMoreYearRequest: "OneMoreYearRequest",
    OnlineConsentRecorded: "OnlineConsentRecorded",
    OnOpenGridTab: "OnOpenGridTab",
    OnOpenShadowTab: "OnOpenShadowTab",
    OpenDonorConference: "OpenDonorConference",
    OpenExternalLink: "OpenExternalLink",
    OperationalAaAtVerdict: "OperationalAaAtVerdict",
    OperationalDamagePercent: "OperationalDamagePercent",
    OperationalHitCount: "OperationalHitCount",
    OperationalHitMax: "OperationalHitMax",
    OperationLaunch: "OperationLaunch",
    OperationRequest: "OperationRequest",
    OperationSlots: "OperationSlots",
    OperationState: "OperationState",
    PaidBoforsAffordableCount: "PaidBoforsAffordableCount",
    PaidBoforsLockedReasonId: "PaidBoforsLockedReasonId",
    PaidGepardAffordableCount: "PaidGepardAffordableCount",
    PaidGepardLockedReasonId: "PaidGepardLockedReasonId",
    PaidPatriotAffordableCount: "PaidPatriotAffordableCount",
    PaidPatriotLockedReasonId: "PaidPatriotLockedReasonId",
    PatriotAmmo: "PatriotAmmo",
    PatriotBlocked: "PatriotBlocked",
    PatriotCount: "PatriotCount",
    PatriotCrew: "PatriotCrew",
    PatriotDroneToggleRequest: "PatriotDroneToggleRequest",
    PatriotInterceptsDrones: "PatriotInterceptsDrones",
    PatriotMaxAmmo: "PatriotMaxAmmo",
    PatriotOffered: "PatriotOffered",
    PatriotPrice: "PatriotPrice",
    PatriotResupplyCost: "PatriotResupplyCost",
    PenaltyThreshold: "PenaltyThreshold",
    PendingProcurementOffer: "PendingProcurementOffer",
    PhaseEndTime: "PhaseEndTime",
    PlaceAABuilding: "PlaceAABuilding",
    PlantId: "PlantId",
    PlantMunicipalRepairHours: "PlantMunicipalRepairHours",
    PlantRepair: "PlantRepair",
    PlantRepairRequest: "PlantRepairRequest",
    PlantShadowOpsRepairHours: "PlantShadowOpsRepairHours",
    PlayerNickname: "PlayerNickname",
    PopulationPeak: "PopulationPeak",
    PopulationPercent: "PopulationPercent",
    Position: "Position",
    PostId: "PostId",
    PowerGridState: "PowerGridState",
    PredictedConscriptionRelease: "PredictedConscriptionRelease",
    PrepareBlackoutLockedReasonId: "PrepareBlackoutLockedReasonId",
    PrepareDisinfoLockedReasonId: "PrepareDisinfoLockedReasonId",
    PrepareDroneLockedReasonId: "PrepareDroneLockedReasonId",
    PrepareOperation: "PrepareOperation",
    Priority: "Priority",
    Procurement100LockedReasonId: "Procurement100LockedReasonId",
    Procurement25LockedReasonId: "Procurement25LockedReasonId",
    Procurement50LockedReasonId: "Procurement50LockedReasonId",
    Procurement75LockedReasonId: "Procurement75LockedReasonId",
    ProcurementCooldown: "ProcurementCooldown",
    ProcurementLevel: "ProcurementLevel",
    ProcurementLevelRequest: "ProcurementLevelRequest",
    ProducerReady: "ProducerReady",
    ProducerReasonId: "ProducerReasonId",
    Production: "Production",
    Progress: "Progress",
    ProtectCriticalInfra: "ProtectCriticalInfra",
    ProtectedBuildings: "ProtectedBuildings",
    ProtestCount: "ProtestCount",
    ProtestRisk: "ProtestRisk",
    PurchaseCounterAttackArsenal: "PurchaseCounterAttackArsenal",
    PurchaseInsider: "PurchaseInsider",
    Quality: "Quality",
    Queue: "Queue",
    RadarDefenses: "RadarDefenses",
    RadarInterceptions: "RadarInterceptions",
    RadarTargets: "RadarTargets",
    RadarThreats: "RadarThreats",
    RandomDisasters: "RandomDisasters",
    Range: "Range",
    RankTier: "RankTier",
    RecallHero: "RecallHero",
    RecallHeroLockedReasonId: "RecallHeroLockedReasonId",
    RecoveryHours: "RecoveryHours",
    RecoveryRate: "RecoveryRate",
    RefreshArenaLeaderboard: "RefreshArenaLeaderboard",
    RefugeeHoursRemaining: "RefugeeHoursRemaining",
    RefugeeHouseholdCount: "RefugeeHouseholdCount",
    RefugeesReceived: "RefugeesReceived",
    RejectLabel: "RejectLabel",
    RejectToast: "RejectToast",
    RemainingSeconds: "RemainingSeconds",
    RepairBillablePercent: "RepairBillablePercent",
    RepairBudgetLive: "RepairBudgetLive",
    RepairCivilian: "RepairCivilian",
    RepairFundingCash: "RepairFundingCash",
    RepairHoursLeft: "RepairHoursLeft",
    RepairPlant: "RepairPlant",
    RepairSlots: "RepairSlots",
    RepairTier: "RepairTier",
    ReportStatus: "ReportStatus",
    ReportStatusKey: "ReportStatusKey",
    ReputationState: "ReputationState",
    ResidentialFocusRange: "ResidentialFocusRange",
    ResidentialMW: "ResidentialMW",
    ResidentialOff: "ResidentialOff",
    RespiteDigitalActive: "RespiteDigitalActive",
    RespitePhysicalActive: "RespitePhysicalActive",
    RespiteSocialActive: "RespiteSocialActive",
    ResupplyGunsLockedReasonId: "ResupplyGunsLockedReasonId",
    ResupplyPatriotLockedReasonId: "ResupplyPatriotLockedReasonId",
    RotationY: "RotationY",
    SampleCount: "SampleCount",
    SanctionDaysRemaining: "SanctionDaysRemaining",
    SanctionsActive: "SanctionsActive",
    SanctionsMarkup: "SanctionsMarkup",
    SanctionsSuppressingCorruption: "SanctionsSuppressingCorruption",
    SanctionTradePenalty: "SanctionTradePenalty",
    SaturationFactor: "SaturationFactor",
    SbuVisit: "SbuVisit",
    SbuVisitCost: "SbuVisitCost",
    SbuVisitLockedReasonId: "SbuVisitLockedReasonId",
    ScandalPenalty: "ScandalPenalty",
    ScenarioStarted: "ScenarioStarted",
    ScenarioType: "ScenarioType",
    Schedule: "Schedule",
    ScheduleActive: "ScheduleActive",
    ScheduleName: "ScheduleName",
    SchemesState: "SchemesState",
    SchoolsPowered: "SchoolsPowered",
    SchoolsTotal: "SchoolsTotal",
    Scope: "Scope",
    SelectDonorDefense: "SelectDonorDefense",
    SelectDonorFunds: "SelectDonorFunds",
    SelectDonorPower: "SelectDonorPower",
    SelectedPresetIndex: "SelectedPresetIndex",
    SendCrashDumps: "SendCrashDumps",
    SendModLog: "SendModLog",
    SendReport: "SendReport",
    Service: "Service",
    ServicesMW: "ServicesMW",
    ServicesOff: "ServicesOff",
    SetBackupPolicy: "SetBackupPolicy",
    SetBackupPolicyLockedReasonId: "SetBackupPolicyLockedReasonId",
    SetBackupPower: "SetBackupPower",
    SetCitySchedule: "SetCitySchedule",
    SetConstructionDelay: "SetConstructionDelay",
    SetDefensePolicy: "SetDefensePolicy",
    SetDifficultyPreset: "SetDifficultyPreset",
    SetDistrictBlackout: "SetDistrictBlackout",
    SetDistrictSchedule: "SetDistrictSchedule",
    SetEmergencyFundWithdraw: "SetEmergencyFundWithdraw",
    SetExportPercent: "SetExportPercent",
    SetFuelSiphonPercent: "SetFuelSiphonPercent",
    SetHeroCounterLockedReasonId: "SetHeroCounterLockedReasonId",
    SetHeroLecturingLockedReasonId: "SetHeroLecturingLockedReasonId",
    SetHeroMode: "SetHeroMode",
    SetInternetMode: "SetInternetMode",
    SetLanguage: "SetLanguage",
    SetMuteAlertAudio: "SetMuteAlertAudio",
    SetMuteCivicAudio: "SetMuteCivicAudio",
    SetMuteCombatAudio: "SetMuteCombatAudio",
    SetMuteDroneAudio: "SetMuteDroneAudio",
    SetNarrativeMode: "SetNarrativeMode",
    SetNeighborEnvy: "SetNeighborEnvy",
    SetPlayerNickname: "SetPlayerNickname",
    SetProcurementLevel: "SetProcurementLevel",
    SetProtectCriticalInfra: "SetProtectCriticalInfra",
    SetRandomDisasters: "SetRandomDisasters",
    SetShadowImportMW: "SetShadowImportMW",
    SetTelemarathonActive: "SetTelemarathonActive",
    SetTelemetryEnabled: "SetTelemetryEnabled",
    SettingsLocalizationState: "SettingsLocalizationState",
    SettingsState: "SettingsState",
    SetUITheme: "SetUITheme",
    SetWinterMultiplier: "SetWinterMultiplier",
    ShadowBalance: "ShadowBalance",
    ShadowExpenses: "ShadowExpenses",
    ShadowHelpSeen: "ShadowHelpSeen",
    ShadowImportAvailability: "ShadowImportAvailability",
    ShadowImportCost: "ShadowImportCost",
    ShadowImportDaysActive: "ShadowImportDaysActive",
    ShadowImportMW: "ShadowImportMW",
    ShadowImportSanctionDays: "ShadowImportSanctionDays",
    ShadowIncome: "ShadowIncome",
    ShadowLocked: "ShadowLocked",
    ShadowOpsRepairCharge: "ShadowOpsRepairCharge",
    ShadowProgramsJson: "ShadowProgramsJson",
    ShadowRepairLockedReasonId: "ShadowRepairLockedReasonId",
    ShadowTotal: "ShadowTotal",
    ShadowTradeExport: "ShadowTradeExport",
    ShadowTradeExportRequest: "ShadowTradeExportRequest",
    ShadowTradeImport: "ShadowTradeImport",
    ShadowTradeImportRequest: "ShadowTradeImportRequest",
    ShadowWallet: "ShadowWallet",
    ShadyContractCount: "ShadyContractCount",
    ShadyPrice: "ShadyPrice",
    ShadyQuality: "ShadyQuality",
    ShadyVendorName: "ShadyVendorName",
    ShockActActive: "ShockActActive",
    ShockHoursRemaining: "ShockHoursRemaining",
    ShockLevel: "ShockLevel",
    ShockTier: "ShockTier",
    ShowDebriefing: "ShowDebriefing",
    SirenActive: "SirenActive",
    SizeMb: "SizeMb",
    SizeX: "SizeX",
    SizeY: "SizeY",
    SizeZ: "SizeZ",
    SocialFeed: "SocialFeed",
    SocialPenaltyProducerReady: "SocialPenaltyProducerReady",
    SocialPenaltyReasonId: "SocialPenaltyReasonId",
    Source: "Source",
    SpotterAction: "SpotterAction",
    SpotterActionRequest: "SpotterActionRequest",
    SpotterCount: "SpotterCount",
    SpotterPenaltyPercent: "SpotterPenaltyPercent",
    SpotterRawPenaltyPercent: "SpotterRawPenaltyPercent",
    SpotterState: "SpotterState",
    StabilityDiscount: "StabilityDiscount",
    State: "State",
    Status: "Status",
    StressPercent: "StressPercent",
    StressZone: "StressZone",
    Success: "Success",
    TaxMultiplier: "TaxMultiplier",
    TelemarathonActive: "TelemarathonActive",
    TelemarathonActiveRequest: "TelemarathonActiveRequest",
    TelemarathonMode: "TelemarathonMode",
    TelemarathonModeRequest: "TelemarathonModeRequest",
    TelemetryEnabled: "TelemetryEnabled",
    TelemetryLockedReasonId: "TelemetryLockedReasonId",
    TensionLevel: "TensionLevel",
    TensionPriceModifierPercent: "TensionPriceModifierPercent",
    TensionPriceMultiplier: "TensionPriceMultiplier",
    TensionStatus: "TensionStatus",
    ThreatComposition: "ThreatComposition",
    ThreatCount: "ThreatCount",
    ThreatsCrashed: "ThreatsCrashed",
    ThreatsExpected: "ThreatsExpected",
    ThreatsHit: "ThreatsHit",
    ThreatsIntercepted: "ThreatsIntercepted",
    ThreatsRemaining: "ThreatsRemaining",
    ThreatsSpawned: "ThreatsSpawned",
    ThreatState: "ThreatState",
    ThreatTargets: "ThreatTargets",
    ThresholdActive: "ThresholdActive",
    ThresholdCutBuildings: "ThresholdCutBuildings",
    ThresholdCutMW: "ThresholdCutMW",
    TimeAgo: "TimeAgo",
    TimeEstimate: "TimeEstimate",
    TimeInPhase: "TimeInPhase",
    Timestamp: "Timestamp",
    TimeText: "TimeText",
    Title: "Title",
    ToastCount: "ToastCount",
    ToastsJson: "ToastsJson",
    ToggleAutoDispatch: "ToggleAutoDispatch",
    ToggleAutoResupply: "ToggleAutoResupply",
    ToggleConscription: "ToggleConscription",
    ToggleCounterOSINT: "ToggleCounterOSINT",
    ToggleDistrictBlackout: "ToggleDistrictBlackout",
    ToggleDistrictCategory: "ToggleDistrictCategory",
    ToggleGlobalConnection: "ToggleGlobalConnection",
    ToggleInternet: "ToggleInternet",
    TogglePanel: "TogglePanel",
    TogglePatriotDroneIntercept: "TogglePatriotDroneIntercept",
    ToggleVIP: "ToggleVIP",
    ToggleVIPBypass: "ToggleVIPBypass",
    TotalAssets: "TotalAssets",
    TotalBuildingsDestroyed: "TotalBuildingsDestroyed",
    TotalCasualties: "TotalCasualties",
    TotalCivilianBuildingsDestroyed: "TotalCivilianBuildingsDestroyed",
    TotalCommercePenalty: "TotalCommercePenalty",
    TotalContractCount: "TotalContractCount",
    TotalCriticalHits: "TotalCriticalHits",
    TotalDamage: "TotalDamage",
    TotalDebt: "TotalDebt",
    TotalDistricts: "TotalDistricts",
    TotalEvacuations: "TotalEvacuations",
    TotalExodus: "TotalExodus",
    TotalExpenses: "TotalExpenses",
    TotalHappinessPenalty: "TotalHappinessPenalty",
    TotalHouseholds: "TotalHouseholds",
    TotalIncome: "TotalIncome",
    TotalLiquidity: "TotalLiquidity",
    TotalMW: "TotalMW",
    TotalRefugees: "TotalRefugees",
    TotalSBUVisits: "TotalSBUVisits",
    TriggerCrisisSweep: "TriggerCrisisSweep",
    TriggerResult: "TriggerResult",
    TrustIndex: "TrustIndex",
    TrustLevel: "TrustLevel",
    TrustLocked: "TrustLocked",
    TrustMessageId: "TrustMessageId",
    TrustTier: "TrustTier",
    Type: "Type",
    UiProfileReport: "UiProfileReport",
    UiTheme: "UiTheme",
    UnsheddableFloorMW: "UnsheddableFloorMW",
    UpgradeIntel: "UpgradeIntel",
    VendorName: "VendorName",
    Version: "Version",
    VulnerableHouseholds: "VulnerableHouseholds",
    Vx: "Vx",
    Vz: "Vz",
    WaitingForLaunchWindow: "WaitingForLaunchWindow",
    WalletBalanceAfter: "WalletBalanceAfter",
    WarDay: "WarDay",
    WaveDataStatus: "WaveDataStatus",
    WaveNumber: "WaveNumber",
    WavePhase: "WavePhase",
    WavePressureAtPeak: "WavePressureAtPeak",
    WavesDefended: "WavesDefended",
    WaveTypePrediction: "WaveTypePrediction",
    WearPercent: "WearPercent",
    WinterMultiplier: "WinterMultiplier",
    WorstCaseRecoveryBallisticOnly: "WorstCaseRecoveryBallisticOnly",
    WorstCaseRecoveryMixed: "WorstCaseRecoveryMixed",
    X: "X",
    Y: "Y",
    Z: "Z",
} as const;

export type BindingKey = Exclude<keyof typeof B, "Group">;
export type BindingName = (typeof B)[BindingKey];

export type ValueBindingKey =
    | "ActiveModalState"
    | "AirDefenseState"
    | "ArenaLastRefreshResult"
    | "ArenaLeaderboard"
    | "ArenaRankTiers"
    | "ArenaWeekly"
    | "ArenaYourPosition"
    | "ArenaYourWeeklyPosition"
    | "AttentionState"
    | "BackupPowerState"
    | "BlackoutRecoveries"
    | "BuckwheatState"
    | "BuildingsDamaged"
    | "CognitiveDistricts"
    | "CognitiveState"
    | "CountermeasuresState"
    | "CrisisDayNumber"
    | "CrisisSweepState"
    | "CurrentAct"
    | "DaysSurvived"
    | "Debug_AaAmmo"
    | "Debug_ABTestProgress"
    | "Debug_ABTestStatus"
    | "Debug_AffectedDistricts"
    | "Debug_BlackoutDuration"
    | "Debug_BlackoutedMW"
    | "Debug_BlackoutPercent"
    | "Debug_BuildingsInBlackout"
    | "Debug_CityIntegrity"
    | "Debug_CityType"
    | "Debug_CommercePenalty"
    | "Debug_CommercialMW"
    | "Debug_Consumption"
    | "Debug_CorruptionHeat"
    | "Debug_CorruptionHistory"
    | "Debug_CorruptionScore"
    | "Debug_CurrentAct"
    | "Debug_EnemyPressure"
    | "Debug_EnemyStance"
    | "Debug_EnemyStanceName"
    | "Debug_ExodusActive"
    | "Debug_ExodusRatePercentPerDay"
    | "Debug_GridCollapsed"
    | "Debug_GridRecoveryHours"
    | "Debug_GridStressHours"
    | "Debug_GridWarfareUnlocked"
    | "Debug_GridZone"
    | "Debug_GridZoneName"
    | "Debug_HappinessPenalty"
    | "Debug_IndustrialMW"
    | "Debug_InfectionRate"
    | "Debug_MediaTrust"
    | "Debug_MoraleFactor"
    | "Debug_OfficeMW"
    | "Debug_PersonalChronicleStatus"
    | "Debug_PowerBalance"
    | "Debug_PowerHistory"
    | "Debug_Production"
    | "Debug_ResidentialMW"
    | "Debug_SeverityHistory"
    | "Debug_SeverityScore"
    | "Debug_ShadowBalance"
    | "Debug_ShadowDailyIncome"
    | "Debug_ShockLevel"
    | "Debug_ShockTier"
    | "Debug_ShockTierName"
    | "Debug_StancePhase"
    | "Debug_StancePhaseName"
    | "Debug_TelemarathonActive"
    | "Debug_TotalDistricts"
    | "Debug_TotalFled"
    | "Debug_TrustLevel"
    | "Debug_WarDay"
    | "Debug_WaveInProgress"
    | "Debug_WaveNumber"
    | "Debug_WavePhase"
    | "Debug_WavePhaseName"
    | "DebugToggleStates"
    | "DefeatCause"
    | "Districts"
    | "DonorState"
    | "EffectiveDiagnostics"
    | "EndlessModeRequest"
    | "ExportState"
    | "FeatureWaveManifest"
    | "FinanceState"
    | "GridHelpSeen"
    | "GridWarfareState"
    | "ImportState"
    | "IntelState"
    | "IntroHudVisible"
    | "IntroPhase"
    | "LoansAvailable"
    | "MaintenanceState"
    | "MapContour"
    | "MissilesIntercepted"
    | "MobilizationState"
    | "NewsFeed"
    | "NewsState"
    | "OneMoreYearRequest"
    | "PopulationPercent"
    | "PowerGridState"
    | "RefugeeHoursRemaining"
    | "RefugeeHouseholdCount"
    | "RefugeesReceived"
    | "ReputationState"
    | "ScenarioType"
    | "SchemesState"
    | "SettingsLocalizationState"
    | "SettingsState"
    | "ShadowHelpSeen"
    | "ShockActActive"
    | "SocialFeed"
    | "SpotterState"
    | "TaxMultiplier"
    | "ThreatState"
    | "ToastCount"
    | "ToastsJson"
    | "TotalRefugees"
    | "TriggerResult"
    | "UiTheme"
    | "WavesDefended";

export type ValueBindingName = (typeof B)[ValueBindingKey];

export interface ValueBindingShape {
    [B.ActiveModalState]: string;
    [B.AirDefenseState]: string;
    [B.ArenaLastRefreshResult]: string;
    [B.ArenaLeaderboard]: string;
    [B.ArenaRankTiers]: string;
    [B.ArenaWeekly]: string;
    [B.ArenaYourPosition]: number;
    [B.ArenaYourWeeklyPosition]: number;
    [B.AttentionState]: string;
    [B.BackupPowerState]: string;
    [B.BlackoutRecoveries]: number;
    [B.BuckwheatState]: string;
    [B.BuildingsDamaged]: number;
    [B.CognitiveDistricts]: string;
    [B.CognitiveState]: string;
    [B.CountermeasuresState]: string;
    [B.CrisisDayNumber]: number;
    [B.CrisisSweepState]: string;
    [B.CurrentAct]: number;
    [B.DaysSurvived]: number;
    [B.Debug_AaAmmo]: number;
    [B.Debug_ABTestProgress]: string;
    [B.Debug_ABTestStatus]: string;
    [B.Debug_AffectedDistricts]: number;
    [B.Debug_BlackoutDuration]: number;
    [B.Debug_BlackoutedMW]: number;
    [B.Debug_BlackoutPercent]: number;
    [B.Debug_BuildingsInBlackout]: number;
    [B.Debug_CityIntegrity]: number;
    [B.Debug_CityType]: string;
    [B.Debug_CommercePenalty]: number;
    [B.Debug_CommercialMW]: number;
    [B.Debug_Consumption]: number;
    [B.Debug_CorruptionHeat]: number;
    [B.Debug_CorruptionHistory]: string;
    [B.Debug_CorruptionScore]: number;
    [B.Debug_CurrentAct]: string;
    [B.Debug_EnemyPressure]: number;
    [B.Debug_EnemyStance]: number;
    [B.Debug_EnemyStanceName]: string;
    [B.Debug_ExodusActive]: number;
    [B.Debug_ExodusRatePercentPerDay]: number;
    [B.Debug_GridCollapsed]: number;
    [B.Debug_GridRecoveryHours]: number;
    [B.Debug_GridStressHours]: number;
    [B.Debug_GridWarfareUnlocked]: boolean;
    [B.Debug_GridZone]: number;
    [B.Debug_GridZoneName]: string;
    [B.Debug_HappinessPenalty]: number;
    [B.Debug_IndustrialMW]: number;
    [B.Debug_InfectionRate]: number;
    [B.Debug_MediaTrust]: number;
    [B.Debug_MoraleFactor]: number;
    [B.Debug_OfficeMW]: number;
    [B.Debug_PersonalChronicleStatus]: string;
    [B.Debug_PowerBalance]: number;
    [B.Debug_PowerHistory]: string;
    [B.Debug_Production]: number;
    [B.Debug_ResidentialMW]: number;
    [B.Debug_SeverityHistory]: string;
    [B.Debug_SeverityScore]: number;
    [B.Debug_ShadowBalance]: number;
    [B.Debug_ShadowDailyIncome]: number;
    [B.Debug_ShockLevel]: number;
    [B.Debug_ShockTier]: number;
    [B.Debug_ShockTierName]: string;
    [B.Debug_StancePhase]: number;
    [B.Debug_StancePhaseName]: string;
    [B.Debug_TelemarathonActive]: number;
    [B.Debug_TotalDistricts]: number;
    [B.Debug_TotalFled]: number;
    [B.Debug_TrustLevel]: number;
    [B.Debug_WarDay]: number;
    [B.Debug_WaveInProgress]: number;
    [B.Debug_WaveNumber]: number;
    [B.Debug_WavePhase]: number;
    [B.Debug_WavePhaseName]: string;
    [B.DebugToggleStates]: string;
    [B.DefeatCause]: number;
    [B.Districts]: string;
    [B.DonorState]: string;
    [B.EffectiveDiagnostics]: boolean;
    [B.EndlessModeRequest]: string;
    [B.ExportState]: string;
    [B.FeatureWaveManifest]: string;
    [B.FinanceState]: string;
    [B.GridHelpSeen]: boolean;
    [B.GridWarfareState]: string;
    [B.ImportState]: string;
    [B.IntelState]: string;
    [B.IntroHudVisible]: boolean;
    [B.IntroPhase]: number;
    [B.LoansAvailable]: boolean;
    [B.MaintenanceState]: string;
    [B.MapContour]: string;
    [B.MissilesIntercepted]: number;
    [B.MobilizationState]: string;
    [B.NewsFeed]: string;
    [B.NewsState]: string;
    [B.OneMoreYearRequest]: string;
    [B.PopulationPercent]: number;
    [B.PowerGridState]: string;
    [B.RefugeeHoursRemaining]: number;
    [B.RefugeeHouseholdCount]: number;
    [B.RefugeesReceived]: number;
    [B.ReputationState]: string;
    [B.ScenarioType]: number;
    [B.SchemesState]: string;
    [B.SettingsLocalizationState]: string;
    [B.SettingsState]: string;
    [B.ShadowHelpSeen]: boolean;
    [B.ShockActActive]: boolean;
    [B.SocialFeed]: string;
    [B.SpotterState]: string;
    [B.TaxMultiplier]: number;
    [B.ThreatState]: string;
    [B.ToastCount]: number;
    [B.ToastsJson]: string;
    [B.TotalRefugees]: number;
    [B.TriggerResult]: string;
    [B.UiTheme]: number;
    [B.WavesDefended]: number;
}

export type DtoFieldKey =
    | "AaAmmo"
    | "AaBofors"
    | "AaGepard"
    | "AaHeritage"
    | "AaMaxAmmo"
    | "AaPatriot"
    | "AaStations"
    | "AcceptLabel"
    | "AcceptShadyEffectiveCost"
    | "AcceptShadyLockedReasonId"
    | "ActiveContractsJson"
    | "ActiveData"
    | "ActiveId"
    | "ActivePriority"
    | "AffordProcurementLockedReasonId"
    | "AidFundsAccessible"
    | "AidFundsOffered"
    | "AidTierId"
    | "AirDefensePlacementRequest"
    | "Altitude"
    | "ArchetypeId"
    | "AreaKm2"
    | "ArrestedAssetsSeized"
    | "ArrestedWalletAfter"
    | "AssetsSeizedSnapshot"
    | "AtRiskPlantCount"
    | "AttackCosts"
    | "AttackType"
    | "AudienceFatigue"
    | "Author"
    | "AuthorName"
    | "AutoCutMW"
    | "AutoDispatchBlockedByVip"
    | "AutoDispatchEnabled"
    | "AutoDispatchSheddedCount"
    | "AutoDispatchShedMW"
    | "AutoDispatchToggleRequest"
    | "AutoResupplyEnabled"
    | "Available"
    | "AvailableLocales"
    | "AvailableThemes"
    | "AvgBlackoutHours"
    | "AvgInfection"
    | "AvgIntegrity"
    | "AvgResistance"
    | "AvgTrauma"
    | "BackupCapacity"
    | "BackupCharge"
    | "BackupPolicy"
    | "BackupPolicyRequest"
    | "BackupPower"
    | "Balance"
    | "BallisticInterceptBallisticOnly"
    | "BallisticInterceptMixed"
    | "BallisticStock"
    | "BallisticTargets"
    | "BaseBribeCost"
    | "BaseDailyCost"
    | "BaseExodusRatePercentPerDay"
    | "BaseInsiderCost"
    | "BasePreset"
    | "BestStreak"
    | "BlackoutProbabilityPct"
    | "BlackoutSource"
    | "BlackoutVulnerability"
    | "BlockedReasonId"
    | "Body"
    | "BoforsAmmo"
    | "BoforsCount"
    | "BoforsCrew"
    | "BoforsMaxAmmo"
    | "BoforsPrice"
    | "BribeAvailability"
    | "BribeCost"
    | "BribeRiskWarning"
    | "BuckwheatTons"
    | "Building"
    | "BuildingName"
    | "BuildingsCutCount"
    | "BuildingsDestroyedThisWeek"
    | "CallToArmsLockedReasonId"
    | "CallToArmsOnCooldown"
    | "CallToArmsRequest"
    | "CalmHours"
    | "CameraX"
    | "CameraZ"
    | "CanAcceptShady"
    | "CanAffordProcurement"
    | "CanBuyInsider"
    | "CanCallToArms"
    | "CanDeployHero"
    | "CanDistribute"
    | "CanEvacuationRun"
    | "CanKickbackRepair"
    | "CanModernizeCorrupt"
    | "CanModernizeHonest"
    | "CanMunicipalRepair"
    | "CanPlaceDonorPatriot"
    | "CanPlaceHeritageBofors"
    | "CanPlacePaidBofors"
    | "CanPlacePaidGepard"
    | "CanPlacePaidPatriot"
    | "CanPrepareBlackout"
    | "CanPrepareDisinfo"
    | "CanPrepareDrone"
    | "CanRecallHero"
    | "CanResupplyGuns"
    | "CanResupplyPatriot"
    | "CanRun"
    | "CanSbuVisit"
    | "CanSetBackupPolicy"
    | "CanSetHeroCounter"
    | "CanSetHeroLecturing"
    | "CanSetProcurement100"
    | "CanSetProcurement25"
    | "CanSetProcurement50"
    | "CanSetProcurement75"
    | "CanShadowRepair"
    | "CanToggleConscription"
    | "CanToggleCounterOSINT"
    | "CanToggleTelemetry"
    | "CanUpgradeIntel"
    | "CapacityHeadroomMW"
    | "CapacityMW"
    | "CasualtiesThisWeek"
    | "Category"
    | "ChargesCount"
    | "ChoiceRequired"
    | "ChoiceType"
    | "CityDispatchableMW"
    | "CitySchedule"
    | "CityScheduleAvailability"
    | "CitySchedulePeriodRequest"
    | "CityStability"
    | "CityTreasury"
    | "CivilianDamage"
    | "CivilianMunicipalRepairHours"
    | "CivilianRepairRequest"
    | "CivilianShadowOpsRepairHours"
    | "CognitiveActive"
    | "CollapseThresholdHours"
    | "CommercePenalty"
    | "CommercialMW"
    | "CommercialOff"
    | "CompromisedDistricts"
    | "ComputedAtGameHours"
    | "ConscriptionLockedReasonId"
    | "ConscriptionReactivationOnCooldown"
    | "ConscriptionToggleRequest"
    | "ConstructionDaysLeft"
    | "ConstructionDelay"
    | "Consumption"
    | "ContextData"
    | "Contractor"
    | "ContractType"
    | "CorruptionSchemeRequest"
    | "CorruptionScore"
    | "CorruptionWindowActive"
    | "Cost"
    | "CountermeasuresPhase"
    | "CounterOSINTActive"
    | "CounterOSINTDailyCost"
    | "CounterOSINTLockedReasonId"
    | "CoveragePct"
    | "CrashDumps"
    | "CriticalHitsThisWeek"
    | "CurrentJournalist"
    | "CurrentLocale"
    | "CurrentOutputMW"
    | "DailyCost"
    | "DailyIncome"
    | "DamageDealt"
    | "DamagePercent"
    | "DaysRemaining"
    | "DebriefingCasualties"
    | "DebriefingCrashed"
    | "DebriefingDamageCost"
    | "DebriefingEfficiency"
    | "DebriefingHits"
    | "DebriefingInfraDamageCost"
    | "DebriefingIntercepted"
    | "DebriefingShotsFired"
    | "DebriefingTotalThreats"
    | "DebriefingWave"
    | "DebtBreakdown"
    | "DebtRestructured"
    | "DebtWarning"
    | "DefensePolicyId"
    | "DefensePolicyName"
    | "DefensePolicyRequest"
    | "DeliveredMW"
    | "Demand"
    | "DeployHeroLockedReasonId"
    | "DifficultyPreset"
    | "DisasterDamagePercent"
    | "DischargingCount"
    | "DiscoveryRisk"
    | "DistributeLockedReasonId"
    | "DistrictIndex"
    | "DistrictInternetToggleRequest"
    | "DistrictName"
    | "DistrictShedMW"
    | "DistrictsOverrideCity"
    | "DistrictToggleRequest"
    | "DominantNarrative"
    | "DonorActiveGenerators"
    | "DonorCooldownDays"
    | "DonorDefenseAvailable"
    | "DonorDefenseLockedReasonId"
    | "DonorDialogActive"
    | "DonorDialogRequest"
    | "DonorExpectedAid"
    | "DonorFundsAmount"
    | "DonorFundsAvailable"
    | "DonorFundsLockedReasonId"
    | "DonorGeneratorCount"
    | "DonorGeneratorMW"
    | "DonorPatriotCredits"
    | "DonorPatriotDays"
    | "DonorPatriotLockedReasonId"
    | "DonorPowerAvailable"
    | "DonorPowerLockedReasonId"
    | "DonorSelectionRequest"
    | "DonorStatus"
    | "DonorUsesRemaining"
    | "DroneInterceptBallisticOnly"
    | "DroneInterceptMixed"
    | "DroneStock"
    | "EarlyWarningMessage"
    | "EffectiveCityMode"
    | "EffectiveCost"
    | "EmergencyFundAvailability"
    | "EmergencyFundBalance"
    | "EmergencyFundWithdraw"
    | "EmergencyResupplyRequest"
    | "EnemyDigitalAxis"
    | "EnemyInterceptChance"
    | "EnemyPhysicalAxis"
    | "EnemySocialAxis"
    | "EnergyFocusRange"
    | "Entity"
    | "EntityIndex"
    | "EntityVersion"
    | "ErrorCount"
    | "EstimatedBallistics"
    | "EstimatedCost"
    | "EstimatedShaheds"
    | "Eta"
    | "EvacuationCost"
    | "EvacuationRunLockedReasonId"
    | "EvasionStatus"
    | "ExodusActive"
    | "ExodusRatePercentPerDay"
    | "Expenses"
    | "ExportAvailability"
    | "ExportedMW"
    | "ExportPercent"
    | "FireCount"
    | "FleetSaturationFactor"
    | "FloorHits"
    | "ForcedOffMW"
    | "FreeHeritageGrant"
    | "FreezeReason"
    | "FuelAvailabilityPercent"
    | "FuelFactor"
    | "FuelSiphonAvailability"
    | "FuelSiphonPercent"
    | "GameHour"
    | "GenerationSources"
    | "GeneratorsRunning"
    | "GepardAmmo"
    | "GepardCount"
    | "GepardCrew"
    | "GepardMaxAmmo"
    | "GepardPrice"
    | "GlobalConnected"
    | "GlobalConnectionStatus"
    | "GlobalOnlineHour"
    | "GlobalOnlineNow"
    | "GlobalOnlineToday"
    | "GlobalOnlineTotal"
    | "GraceWindowHours"
    | "GridExportMW"
    | "GridFrequency"
    | "GridStatus"
    | "GridWarfareUnlocked"
    | "GunsResupplyCost"
    | "HasBlockedItems"
    | "HasExploded"
    | "HasInsider"
    | "HasInternet"
    | "HasProgram"
    | "HasResult"
    | "HeadroomWarningMW"
    | "Heat"
    | "HeatLevel"
    | "HeritageAmmo"
    | "HeritageBoforsCount"
    | "HeritageBoforsLockedReasonId"
    | "HeritageCredits"
    | "HeritageCreditsMax"
    | "HeritageCrew"
    | "HeritageMaxAmmo"
    | "HeroActionRequest"
    | "HeroDeployCost"
    | "HeroInfectionReduction"
    | "HeroRecoveryBonus"
    | "HeroStatus"
    | "HitCount"
    | "HospitalsPowered"
    | "HospitalsTotal"
    | "HouseholdsInfected"
    | "HouseholdsUnderBlackout"
    | "HouseholdsUnderImpact"
    | "HouseholdsWithEnvy"
    | "Icon"
    | "Id"
    | "IdentifyConfirmed"
    | "IdentifyFocusActive"
    | "IdentifyProgress"
    | "IdentifyTrackedEntity"
    | "Income"
    | "Index"
    | "IndustrialMW"
    | "IndustrialOff"
    | "InfectionRate"
    | "InfraFocusRange"
    | "InsiderCost"
    | "InsiderLockedReasonId"
    | "InsiderRequest"
    | "Integrity"
    | "IntelReportLabel"
    | "IntelUpgradeCost"
    | "IntelUpgradeLevel"
    | "IntelUpgradeLockedReasonId"
    | "IntelUpgradeRequest"
    | "InternetDisabled"
    | "InternetMode"
    | "InternetModeRequest"
    | "InvestigationProgress"
    | "IpsoActive"
    | "IpsoDistrictCount"
    | "IpsoIntensity"
    | "IpsoTotalDistricts"
    | "IsAiGenerated"
    | "IsArrested"
    | "IsAtRisk"
    | "IsAutoShedded"
    | "IsCompromised"
    | "IsConscriptionActive"
    | "IsDestroyed"
    | "IsExpanded"
    | "IsFrozen"
    | "IsFrozenOut"
    | "IsIdentified"
    | "IsInShock"
    | "IsManpowerCritical"
    | "IsManpowerOvercommitted"
    | "IsMassiveStrike"
    | "IsOfficial"
    | "IsRecoverableBallisticOnly"
    | "IsRecoverableMixed"
    | "IsRepairable"
    | "IsRepairing"
    | "IsSanctioned"
    | "IsShady"
    | "IsUncensored"
    | "IsUnderConstruction"
    | "IsUnzoned"
    | "IsVIP"
    | "IsVIPBypass"
    | "IsWarFatigued"
    | "KickbackAmount"
    | "KickbackEarned"
    | "KickbackOffer"
    | "KickbackRepairAmount"
    | "KickbackRepairLockedReasonId"
    | "LanguagePreference"
    | "LastChoiceRequestResult"
    | "LastChoiceResult"
    | "LastDistributeResult"
    | "LegalExportMW"
    | "LegalImportMW"
    | "Lifetime"
    | "LocaleRequest"
    | "LocaleVersion"
    | "LocalizationStrings"
    | "LockedBalance"
    | "LockedReasonId"
    | "MaintenanceContractRequest"
    | "ManpowerAvailable"
    | "ManpowerBasePool"
    | "ManpowerCasualties"
    | "ManpowerFatigueFactor"
    | "ManpowerMoraleFactor"
    | "ManpowerPatriotismFactor"
    | "ManpowerPercent"
    | "ManpowerTotal"
    | "ManpowerUsed"
    | "MapBounds"
    | "Max"
    | "MaxHits"
    | "MaxHours"
    | "MaxShadowImportMW"
    | "MaxX"
    | "MaxZ"
    | "MedianCollapseDay"
    | "MediaTrust"
    | "Message"
    | "Min"
    | "MinEtaSeconds"
    | "MinFloorHits"
    | "MinHours"
    | "MinX"
    | "MinZ"
    | "MissilesSpentOnDrones"
    | "Mode"
    | "ModernizationRequest"
    | "ModernizeCorruptLockedReasonId"
    | "ModernizeHonestLockedReasonId"
    | "Mood"
    | "MunicipalKickbackRepairCharge"
    | "MunicipalRepairCharge"
    | "MunicipalRepairLockedReasonId"
    | "MuteAlertAudio"
    | "MuteCivicAudio"
    | "MuteCombatAudio"
    | "MuteDroneAudio"
    | "Name"
    | "NarrativeMode"
    | "NeighborEnvy"
    | "NetworkConnectionEnabled"
    | "Nickname"
    | "NicknameChangesRemaining"
    | "NicknameInitialized"
    | "NicknameRequest"
    | "NoActiveThreatsLabel"
    | "NoiseLevel"
    | "ObjectiveProgress"
    | "OfferFrequencyMult"
    | "OfficeMW"
    | "OfficeOff"
    | "OfficialPrice"
    | "OfficialQuality"
    | "OfficialTreasury"
    | "OfficialVendorName"
    | "OffshoreBalance"
    | "OnlineConsentRecorded"
    | "OperationalAaAtVerdict"
    | "OperationalDamagePercent"
    | "OperationalHitCount"
    | "OperationalHitMax"
    | "OperationRequest"
    | "OperationSlots"
    | "OperationState"
    | "PaidBoforsAffordableCount"
    | "PaidBoforsLockedReasonId"
    | "PaidGepardAffordableCount"
    | "PaidGepardLockedReasonId"
    | "PaidPatriotAffordableCount"
    | "PaidPatriotLockedReasonId"
    | "PatriotAmmo"
    | "PatriotBlocked"
    | "PatriotCount"
    | "PatriotCrew"
    | "PatriotDroneToggleRequest"
    | "PatriotInterceptsDrones"
    | "PatriotMaxAmmo"
    | "PatriotOffered"
    | "PatriotPrice"
    | "PatriotResupplyCost"
    | "PenaltyThreshold"
    | "PendingProcurementOffer"
    | "PhaseEndTime"
    | "PlantId"
    | "PlantMunicipalRepairHours"
    | "PlantRepairRequest"
    | "PlantShadowOpsRepairHours"
    | "PlayerNickname"
    | "PopulationPeak"
    | "Position"
    | "PostId"
    | "PredictedConscriptionRelease"
    | "PrepareBlackoutLockedReasonId"
    | "PrepareDisinfoLockedReasonId"
    | "PrepareDroneLockedReasonId"
    | "Priority"
    | "Procurement100LockedReasonId"
    | "Procurement25LockedReasonId"
    | "Procurement50LockedReasonId"
    | "Procurement75LockedReasonId"
    | "ProcurementCooldown"
    | "ProcurementLevel"
    | "ProcurementLevelRequest"
    | "ProducerReady"
    | "ProducerReasonId"
    | "Production"
    | "Progress"
    | "ProtectCriticalInfra"
    | "ProtectedBuildings"
    | "ProtestCount"
    | "ProtestRisk"
    | "Quality"
    | "Queue"
    | "RadarDefenses"
    | "RadarInterceptions"
    | "RadarTargets"
    | "RadarThreats"
    | "RandomDisasters"
    | "Range"
    | "RankTier"
    | "RecallHeroLockedReasonId"
    | "RecoveryHours"
    | "RecoveryRate"
    | "RejectLabel"
    | "RemainingSeconds"
    | "RepairBillablePercent"
    | "RepairBudgetLive"
    | "RepairFundingCash"
    | "RepairHoursLeft"
    | "RepairSlots"
    | "RepairTier"
    | "ReportStatus"
    | "ReportStatusKey"
    | "ResidentialFocusRange"
    | "ResidentialMW"
    | "ResidentialOff"
    | "RespiteDigitalActive"
    | "RespitePhysicalActive"
    | "RespiteSocialActive"
    | "ResupplyGunsLockedReasonId"
    | "ResupplyPatriotLockedReasonId"
    | "RotationY"
    | "SampleCount"
    | "SanctionDaysRemaining"
    | "SanctionsActive"
    | "SanctionsMarkup"
    | "SanctionsSuppressingCorruption"
    | "SanctionTradePenalty"
    | "SaturationFactor"
    | "SbuVisitCost"
    | "SbuVisitLockedReasonId"
    | "ScandalPenalty"
    | "ScenarioStarted"
    | "Schedule"
    | "ScheduleActive"
    | "ScheduleName"
    | "SchoolsPowered"
    | "SchoolsTotal"
    | "Scope"
    | "SelectedPresetIndex"
    | "Service"
    | "ServicesMW"
    | "ServicesOff"
    | "SetBackupPolicyLockedReasonId"
    | "SetHeroCounterLockedReasonId"
    | "SetHeroLecturingLockedReasonId"
    | "ShadowBalance"
    | "ShadowExpenses"
    | "ShadowImportAvailability"
    | "ShadowImportCost"
    | "ShadowImportDaysActive"
    | "ShadowImportMW"
    | "ShadowImportSanctionDays"
    | "ShadowIncome"
    | "ShadowLocked"
    | "ShadowOpsRepairCharge"
    | "ShadowProgramsJson"
    | "ShadowRepairLockedReasonId"
    | "ShadowTotal"
    | "ShadowTradeExportRequest"
    | "ShadowTradeImportRequest"
    | "ShadowWallet"
    | "ShadyContractCount"
    | "ShadyPrice"
    | "ShadyQuality"
    | "ShadyVendorName"
    | "ShockHoursRemaining"
    | "ShockLevel"
    | "ShockTier"
    | "ShowDebriefing"
    | "SirenActive"
    | "SizeMb"
    | "SizeX"
    | "SizeY"
    | "SizeZ"
    | "SocialPenaltyProducerReady"
    | "SocialPenaltyReasonId"
    | "Source"
    | "SpotterActionRequest"
    | "SpotterCount"
    | "SpotterPenaltyPercent"
    | "SpotterRawPenaltyPercent"
    | "StabilityDiscount"
    | "State"
    | "Status"
    | "StressPercent"
    | "StressZone"
    | "Success"
    | "TelemarathonActive"
    | "TelemarathonActiveRequest"
    | "TelemarathonModeRequest"
    | "TelemetryEnabled"
    | "TelemetryLockedReasonId"
    | "TensionLevel"
    | "TensionPriceModifierPercent"
    | "TensionPriceMultiplier"
    | "TensionStatus"
    | "ThreatComposition"
    | "ThreatCount"
    | "ThreatsCrashed"
    | "ThreatsExpected"
    | "ThreatsHit"
    | "ThreatsIntercepted"
    | "ThreatsRemaining"
    | "ThreatsSpawned"
    | "ThreatTargets"
    | "ThresholdActive"
    | "ThresholdCutBuildings"
    | "ThresholdCutMW"
    | "TimeAgo"
    | "TimeEstimate"
    | "TimeInPhase"
    | "Timestamp"
    | "TimeText"
    | "Title"
    | "TotalAssets"
    | "TotalBuildingsDestroyed"
    | "TotalCasualties"
    | "TotalCivilianBuildingsDestroyed"
    | "TotalCommercePenalty"
    | "TotalContractCount"
    | "TotalCriticalHits"
    | "TotalDamage"
    | "TotalDebt"
    | "TotalDistricts"
    | "TotalEvacuations"
    | "TotalExodus"
    | "TotalExpenses"
    | "TotalHappinessPenalty"
    | "TotalHouseholds"
    | "TotalIncome"
    | "TotalLiquidity"
    | "TotalMW"
    | "TotalSBUVisits"
    | "TrustIndex"
    | "TrustLevel"
    | "TrustLocked"
    | "TrustMessageId"
    | "TrustTier"
    | "Type"
    | "UnsheddableFloorMW"
    | "VendorName"
    | "Version"
    | "VulnerableHouseholds"
    | "Vx"
    | "Vz"
    | "WaitingForLaunchWindow"
    | "WalletBalanceAfter"
    | "WarDay"
    | "WaveDataStatus"
    | "WaveNumber"
    | "WavePhase"
    | "WavePressureAtPeak"
    | "WaveTypePrediction"
    | "WearPercent"
    | "WinterMultiplier"
    | "WorstCaseRecoveryBallisticOnly"
    | "WorstCaseRecoveryMixed"
    | "X"
    | "Y"
    | "Z";

export type DtoFieldName = (typeof B)[DtoFieldKey];
