using Unity.Entities;
using Unity.Mathematics;
using CivicSurvival.Core.Types;

namespace CivicSurvival.Domains.AirDefense.Jobs
{
    /// <summary>
    /// Burst-compatible data for a ready AA installation.
    /// Collected once per frame from ECS components.
    /// NOTE: Entity stored as Index+Version to avoid vanilla orphan detection.
    /// </summary>
    public struct AAData
    {
        public int EntityIndex;
        public int EntityVersion;
        public float3 Position;
        public float RangeSq;
        // InterceptChance = vs Shahed (drones); InterceptChanceBallistic = vs missiles (Patriot only, 0 otherwise).
        public float InterceptChance;
        public float InterceptChanceBallistic;
        public float CooldownDuration;
        public int CurrentAmmo;
        public int MaxAmmo;
        public AAType Type;
        // Source AA object entity (the placed StaticObjectPrefab prop) — used by LOS to skip self-occlusion.
        public BuildingRef Building;
        // Transform chunk change-version of the prop at cache-build time. LiveAACacheSystem compares this
        // to the prop's current chunk change-version each frame to detect an in-place relocation (Move It /
        // vanilla relocate) — a Transform VALUE change that does not bump the AA order version.
        public uint TransformVersion;

        public Entity GetEntity() => new Entity { Index = EntityIndex, Version = EntityVersion };
    }

    /// <summary>
    /// Burst-compatible data for an active threat.
    /// Collected once per frame from ECS components.
    /// NOTE: Entity stored as Index+Version to avoid vanilla orphan detection.
    /// </summary>
    public struct ThreatData
    {
        public int EntityIndex;
        public int EntityVersion;
        public float3 Position;
        public float DistanceToTarget;
        public TargetCategory Category;
        public int MissedShots;
        /// <summary>True if player has PriorityTarget on this threat (engagement pipeline).</summary>
        public bool IsPriority;

        public Entity GetEntity() => new Entity { Index = EntityIndex, Version = EntityVersion };
    }

    /// <summary>
    /// Candidate engagement pair (AA can potentially engage this threat).
    /// Generated by ThreatAAMatchJob, scored by EngagementScoringJob.
    /// </summary>
    public struct EngagementCandidate
    {
        public int ThreatIndex;
        public int AAIndex;
        public float DistanceSq;
        // Pre-computed distance (sqrt done once at match-time, not per scoring frame)
        public float Distance;
        public float Score;
        public bool IsOverResidential;
        public bool PassedLOS;
        // S16a-1 FIX: Store threat entity identity for cross-frame validation
        public int ThreatEntityIndex;
        public int ThreatEntityVersion;
        // Cache AA stats at match-time to avoid re-fetch in FireControlExecutor
        public float InterceptChance;
        public float CooldownDuration;
    }

    /// <summary>
    /// Configuration for scoring job (cached from BalanceConfig).
    /// </summary>
    public struct ScoringConfig
    {
        public float ResidentialRadiusSq;
        public DefensePolicy Policy;
        public float CriticalDistance;
    }
}
