// <auto-generated>
// Generated from Docs/Contracts/telemetry.contract.yaml (v1.15)
// DO NOT EDIT MANUALLY - Run: python scripts/generate.py
// </auto-generated>

namespace CivicSurvival.Core.Types
{
    /// <summary>Donor trust level based on corruption score</summary>
    public enum TrustLevel
    {
        /// <summary>75-100% trust: All options at full capacity</summary>
        Full = 0,

        /// <summary>50-74% trust: Funds + Power, no Defense</summary>
        Partial = 1,

        /// <summary>25-49% trust: Only reduced Funds</summary>
        Minimal = 2,

        /// <summary>0-24% trust: Sanctions applied, no aid</summary>
        Refused = 3
    }

    /// <summary>Scenario narrative act/phase</summary>
    public enum Act : byte
    {
        /// <summary>Ominous signs until the city reaches the war milestone</summary>
        PreWar = 0,

        /// <summary>First 3-7 days: chaos, no control</summary>
        Crisis = 1,

        /// <summary>Population leaves, refugee crisis</summary>
        Exodus = 2,

        /// <summary>Learning to survive: schedules, donors</summary>
        Adaptation = 3,

        /// <summary>Long-term survival</summary>
        Routine = 4
    }

}