/**
 * Auto-generated trigger payload signatures.
 * Source: Tools/binding-manifest.generated.json
 * Run: node Tools/sync-binding-codegen.js
 *
 * Each entry maps a trigger constant value (B.X) to its expected payload tuple,
 * augmenting TriggerArgRegistry so triggerCivic(B.X, ...args) is type-checked.
 */
import type { B } from "../hooks/bindingNames.generated";
import type { EntityRef } from "./entityRef";


declare module "../hooks/typedTrigger" {
    interface TriggerArgRegistry {
        [B.AcceptOfficialContract]: [number, number, number];
        [B.AcceptShadyContract]: [number, number, number];
        [B.AcceptToast]: [number];
        [B.CallToArms]: [];
        [B.CancelOperation]: [string];
        [B.ClearErrors]: [];
        [B.CloseDonorConference]: [];
        [B.CopyReport]: [];
        [B.Debug_SetAct]: [number];
        [B.DebugDemolish1Building]: [];
        [B.DebugDemolishBuildingsToggle]: [];
        [B.DebugDestroyAllDrones]: [];
        [B.DebugExplodeDrone]: [];
        [B.DebugForceCrash]: [];
        [B.DebugForceDayChange]: [];
        [B.DebugForceGridCollapse]: [];
        [B.DebugForceWave]: [];
        [B.DebugGeneratePersonalChronicle]: [];
        [B.DebugGlitchDrone]: [];
        [B.DebugKill500CiviliansNative]: [];
        [B.DebugResetGridStress]: [];
        [B.DebugRunPreset]: [number];
        [B.DebugSetCityIntegrity]: [number];
        [B.DebugSetCorruption]: [number];
        [B.DebugSetDusk]: [];
        [B.DebugSetEnemyPressure]: [number];
        [B.DebugSetMidnight]: [];
        [B.DebugSetMoraleFactor]: [number];
        [B.DebugSetShock]: [number];
        [B.DebugSetStress]: [number];
        [B.DebugSetTrust]: [number];
        [B.DebugSkipPhase]: [];
        [B.DebugSpawn10Ballistics]: [];
        [B.DebugSpawn1Ballistic]: [];
        [B.DebugSpawn1Drone]: [];
        [B.DebugSpawn25Drones]: [];
        [B.DebugSpawnWaveDusk]: [];
        [B.DebugTestExplosion]: [];
        [B.DebugTestTracer]: [];
        [B.DebugToggleExodus]: [];
        [B.DebugToggleSystem]: [string, boolean];
        [B.DeclineProcurement]: [number, number];
        [B.DeployHero]: [number];
        [B.DismissArrested]: [];
        [B.DismissCollapseModal]: [];
        [B.DismissCorruptionOffer]: [];
        [B.DismissDebriefing]: [];
        [B.DismissDefeat]: [];
        [B.DismissExodusWarning]: [];
        [B.DismissFirstDonorAid]: [];
        [B.DismissFirstStrike]: [];
        [B.DismissFirstSuccessfulDefense]: [];
        [B.DismissGeneratorEra]: [];
        [B.DismissGhostTown]: [];
        [B.DismissGridCollapse]: [];
        [B.DismissGridCritical]: [];
        [B.DismissModLoadFailure]: [];
        [B.DismissRefugeeModal]: [];
        [B.DismissSpotterAlert]: [];
        [B.DismissToast]: [number];
        [B.DismissWarBegins]: [];
        [B.DismissWarFatigue]: [];
        [B.DismissWhoStaysBehind]: [];
        [B.DistributeAid]: [number];
        [B.EmergencyResupply]: [number];
        [B.EndlessMode]: [];
        [B.Evacuation]: [];
        [B.ExecuteOperation]: [string];
        [B.FocusNextThreat]: [];
        [B.FocusRadarDefense]: [number, number];
        [B.FocusRadarThreat]: [EntityRef];
        [B.FocusThreat]: [EntityRef];
        [B.JsLog]: [string];
        [B.LaunchDistrictModernization]: [number];
        [B.MakeInvestigationChoice]: [number];
        [B.MakePoliceChoice]: [number];
        [B.MarkGridHelpSeen]: [];
        [B.MarkShadowHelpSeen]: [];
        [B.OnAcceptReality]: [];
        [B.OneMoreYear]: [];
        [B.OnOpenGridTab]: [];
        [B.OnOpenShadowTab]: [];
        [B.OpenDonorConference]: [];
        [B.OpenExternalLink]: [number];
        [B.PlaceAABuilding]: [string];
        [B.PrepareOperation]: [string];
        [B.PurchaseCounterAttackArsenal]: [number, number];
        [B.PurchaseInsider]: [];
        [B.RecallHero]: [];
        [B.RefreshArenaLeaderboard]: [];
        [B.RejectToast]: [number];
        [B.RepairCivilian]: [EntityRef, number];
        [B.RepairPlant]: [number, number];
        [B.SbuVisit]: [];
        [B.SelectDonorDefense]: [];
        [B.SelectDonorFunds]: [];
        [B.SelectDonorPower]: [];
        [B.SendCrashDumps]: [string];
        [B.SendModLog]: [];
        [B.SendReport]: [];
        [B.SetBackupPolicy]: [number];
        [B.SetBackupPower]: [boolean];
        [B.SetCitySchedule]: [number];
        [B.SetConstructionDelay]: [boolean];
        [B.SetDefensePolicy]: [number];
        [B.SetDifficultyPreset]: [number];
        [B.SetDistrictBlackout]: [number, number];
        [B.SetDistrictSchedule]: [number, number];
        [B.SetEmergencyFundWithdraw]: [number];
        [B.SetExportPercent]: [number];
        [B.SetFuelSiphonPercent]: [number];
        [B.SetHeroMode]: [number];
        [B.SetInternetMode]: [number];
        [B.SetLanguage]: [number];
        [B.SetMuteAlertAudio]: [boolean];
        [B.SetMuteCivicAudio]: [boolean];
        [B.SetMuteCombatAudio]: [boolean];
        [B.SetMuteDroneAudio]: [boolean];
        [B.SetNarrativeMode]: [number];
        [B.SetNeighborEnvy]: [boolean];
        [B.SetPlayerNickname]: [string];
        [B.SetProcurementLevel]: [number];
        [B.SetProtectCriticalInfra]: [boolean];
        [B.SetRandomDisasters]: [boolean];
        [B.SetShadowImportMW]: [number];
        [B.SetTelemarathonActive]: [boolean];
        [B.SetTelemetryEnabled]: [boolean];
        [B.SetUITheme]: [number];
        [B.SetWinterMultiplier]: [boolean];
        [B.ToggleAutoDispatch]: [];
        [B.ToggleAutoResupply]: [boolean];
        [B.ToggleConscription]: [];
        [B.ToggleCounterOSINT]: [];
        [B.ToggleDistrictBlackout]: [number];
        [B.ToggleDistrictCategory]: [number];
        [B.ToggleGlobalConnection]: [boolean];
        [B.ToggleInternet]: [number];
        [B.TogglePanel]: [];
        [B.TogglePatriotDroneIntercept]: [boolean];
        [B.ToggleVIP]: [number];
        [B.ToggleVIPBypass]: [number];
        [B.TriggerCrisisSweep]: [number];
        [B.UiProfileReport]: [string];
        [B.UpgradeIntel]: [];
    }
}
